"""empty message

Revision ID: 26d9d107e2be
Revises: cf1ae901ffcc
Create Date: 2022-10-12 19:20:56.230907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d9d107e2be'
down_revision = 'cf1ae901ffcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('access_key_id', sa.String(length=200), nullable=True),
    sa.Column('secret_access_key', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
